# Generated by Django 4.1.7 on 2023-06-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_department_registern_delete_register_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registern',
        ),
    ]
